# Generated by Django 5.2.6 on 2025-10-02 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tributemessage',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
