# Generated by Django 5.2.6 on 2025-10-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tribute', '0002_tributemessage_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tributemessage',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='tributemessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
